### ISSUE TITLE
[QST] How do I install the latest `atop` version on Ubuntu?

### ISSUE THREAD

**Issue by NightMachinary** [Atoptool/atop#186]
I want to use `atopgpud` on Google Colab. So I need to install the latest version of `atop` on their Ubuntu machines. I have tried:

```zsh
aria2c 'https://www.atoptool.nl/download/atop-2.7.1-1.el7.x86_64.rpm'
sudo apt-get install -y alien
sudo alien -i atop*.rpm

pip install -U nvidia-ml-py
```

But running `atopgpud` throws this error:
```
# atopgpud
--- Logging error ---
Traceback (most recent call last):
  File "/usr/sbin/atopgpud", line 242, in main
    pynvml.nvmlInit()
  File "/usr/local/lib/python3.7/dist-packages/pynvml.py", line 1640, in nvmlInit
    nvmlInitWithFlags(0)
  File "/usr/local/lib/python3.7/dist-packages/pynvml.py", line 1630, in nvmlInitWithFlags
    _nvmlCheckReturn(ret)
  File "/usr/local/lib/python3.7/dist-packages/pynvml.py", line 784, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_DriverNotLoaded: Driver Not Loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.7/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/sbin/atopgpud", line 598, in <module>
    main()
  File "/usr/sbin/atopgpud", line 244, in main
    logging.error("Shared lib 'libnvidia-ml' probably not installed!")
Message: "Shared lib 'libnvidia-ml' probably not installed!"
Arguments: ()
```

PS: What's the difference between the `el7` and `el8` `rpm` packages?

**Comment by Atoptool** [comment]
I do not have an Ubuntu-based system with NVIDIA gpu so I can not really test this.
You are anyhow missing the libnvidia-ml library.  I installed such library in an Ubuntu container with command `apt get libnvidia-ml-dev` but I do not know if that is the correct version.

**Comment by thiswillbeyourgithub** [comment]
3 years later and I just want to say that I too am wondering the best way to get the latest atop on ubuntu. I am on ubuntu 22 and I tried building it and ended breaking apt because of libglib something issues. I was super happy to learn by happenstance that atop existed and allowed to get back in time and see what process was causing some slow downs etc retroactively and the idea to monitor my gpu too seems awesome!
